# Generated by Django 4.2.7 on 2023-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_savedevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedevents',
            name='favorite',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='date',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='image',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='link',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='state',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='time',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='savedevents',
            name='venue',
            field=models.CharField(max_length=64),
        ),
    ]
