# Generated by Django 4.2.7 on 2024-03-26 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalproject', '0005_savedevents_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=128)),
                ('date', models.CharField(blank=True, max_length=32)),
                ('time', models.CharField(blank=True, max_length=16)),
                ('content', models.CharField(blank=True, max_length=256)),
                ('favorite', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
