# Generated by Django 4.2.7 on 2024-03-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0006_savednotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednotes',
            name='username',
            field=models.CharField(default='hello', max_length=16),
            preserve_default=False,
        ),
    ]
